/rat/physics_list/OmitMuonicProcesses true
/rat/physics_list/OmitHadronicProcesses true

/rat/db/set MC thin_factor 1.0
/rat/db/set DETECTOR geo_file "geo/snoplusnative.geo"
/rat/db/set GEO[inner_av] material "labppo_2p2_scintillator"
/rat/db/set GEO[av] position [0.,0.,186.5]

/run/initialize

/rat/proc frontend
/rat/proc trigger
/rat/proc eventbuilder
/rat/proc calibratePMT
/rat/proc count
/rat/procset update 1


/rat/proc prune
/rat/procset prune "mc.hits,mc.pmts.photons"

/rat/proc outroot
/rat/procset file "test1output.root"

/generator/add combo gun:fill
/generator/vtx/set e- 0 0 0 2.5
/generator/pos/set 0.0 0.0 0.0
/generator/rate/set 1

/rat/run/start 10
exit









