####################################################################
### Template macro for reconstructing presimulated events with Quad
### Options are written in by scripts in job_sub
####################################################################

/rat/inroot/load ${input_file}

/run/initialize

/rat/proc count # An example processor
/rat/procset update 5

/rat/proc fitter
/rat/procset method "quad"

/rat/proc outroot
/rat/procset file "${output_file}"

/rat/inroot/read
exit
